tree_menu/menu/urls.py
from django.urls import path
from . import views


app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
]

tree_menu/core/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
# Create your models here.


class main_menu(MPTTModel):
    name = models.CharField(max_length=100, unique=True)
    url = models.CharField('Сcылка', max_length=255)
    position = models.PositiveIntegerField('Позиция', default=1)
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',)

    class MPTTMeta:
        order_insertion_by = ['position']

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'Пункт меню'
        verbose_name_plural = 'Пункты меню'

tree_menu/menu/models.py
from django.db import models


class Menu(models.Model):
    name = models.CharField('Название', max_length=100)
    ulr = models.CharField('Ссылка', max_length=255)
    position = models.PositiveIntegerField('Позиция', default=1)

    def __str__(self):
        return self.name


class Meta:
    ordering = ('position',)
    verbose_name = 'Пункт меню'
    verbose_name_plural = 'Пункты меню'

tree_menu/menu/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'menu/index.html',)

tree_menu/menu/templates/base.html
{% load draw_menu %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}django-simple-menu example{% endblock %}</title>

    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"
    >
      <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"


    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
<header>
{% draw_menu %}
</header>
{% block body %}

{% endblock body %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

tree_menu/menu/templates/menu/index.html
{% extends 'base.html' %}

tree_menu/menu/templates/menu/menu.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'menu:index' %}">Тестовый сайт</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03"
                aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample03">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                {% for menu_item in menu_items %}

                    {% if menu_item.get_children %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown03"
                               data-bs-toggle="dropdown" aria-expanded="false">{{ menu_item }}</a>
                            <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                {% for m_item in menu_item.get_children %}
                                    <li><a class="dropdown-item" href="{{ m_item.url }}">{{ m_item }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{{ menu_item.url }}">{{ menu_item }}</a>
                        </li>
                    {% endif %}

                {% endfor %}
            </ul>
            <form>
                <input class="form-control" type="text" placeholder="Search" aria-label="Search">
            </form>
        </div>
    </div>
</nav>